baseURL = "https://nevetS.github.io"
defaultContentLanguage = "en"
disqusShortname = "test"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
theme = "simplicity"
title = "Steve Kallestad"
[author]
  gravatarEmail = "kallestad@gmail.com"
  homepageText = "Steve"
  name = "Steve Kallestad"
  rss = "/posts/index.xml"
[imaging]
  anchor = "smart"
  resampleFilter = "box"
  quality = 75
[[menu.pages]]
  name = "Projects"
  weight = -100
  identifier = "projects"
  url = "/projects/"
[[menu.pages]]
  name = "Photos"
  weight = -90
  identifier = "photos"
  url = "/photos/"
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[params]
  adsenseClient = ''
  adsenseSlot = ''
  description = "A blog about everything."
#  licence = "proprietary information"
  displayPostLanguage = true
[permalinks]
  posts = "/:year/:month/:day/:slug/"
[pygmentsOptions]
  linenos = false
